### ISSUE TITLE
Feature: Adding contributors section to the README.md file. 

### ISSUE THREAD

**Issue by kalyani2003** [Audio-AGI/AudioSep#38]
There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
The Contributors section in a README.md file is important as it acknowledges and gives credit to those who have contributed to a project, fosters community and collaboration, adds transparency and accountability, and helps document the project's history for current and future maintainers. It also serves as a form of recognition, motivating contributors to continue their efforts.
![contributors](https://github.com/Audio-AGI/AudioSep/assets/84217977/bff09c31-0f37-4726-bdc5-76b0930e94b9)

**Comment by kalyani2003** [comment]
@liuxubo717 Kindly assign me this issue, I want to work on it! Thank You.

**Comment by liuxubo717** [comment]
Happy to assign this task with you!
