### ISSUE TITLE
Requesting Code reference for metrics calculation

### ISSUE THREAD

**Issue by stonelazy** [Audio-AGI/AudioSep#5]
Team, I was wondering if you haven't included code reference for evaluation metrics such as CSIG,CBAK, COVL, SSNR etc.. ? Do you have any plans for this please ?

**Comment by liuxubo717** [comment]
The code is already here: https://github.com/Audio-AGI/AudioSep/blob/main/utils.py

I'll release the evaluation benchmark soon!

**Comment by stonelazy** [comment]
Thanks for the revert. Am sorry, but i couldn't see evaluation code for the these metrics specifically CSIG,CBAK,COVL,SSNR.

**Comment by liuxubo717** [comment]
Thanks for the reminder, Will update it ASAP.

**Comment by liuxubo717** [comment]
For speech enhancement metrics, I use from pesq import pesq
import pysepm
